[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.mypy]
strict = true
python_version = "3.7"

[tool.pylint.messages]
disable = ["R0801"]
